# Generated by Django 4.1.1 on 2022-09-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_code', models.CharField(max_length=3)),
                ('description', models.TextField()),
                ('URL', models.URLField()),
                ('response_type', models.CharField(max_length=20)),
            ],
        ),
    ]
